#!/usr/bin/env ruby

forge 'https://forgeapi.puppetlabs.com'

#Base
mod 'puppetlabs-lvm', '0.7.0'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppetlabs-firewall', '1.11.0'
mod 'puppet-selinux', '1.5.1'
mod 'puppetlabs-postgresql', '5.12.1'
mod 'puppet-puppetserver', '3.0.0'
mod 'puppetlabs-puppetdb', '6.0.2'
mod 'puppet-hiera', '3.0.0'

#Toegevoegd voor minimale base rol zonder agents
mod 'cmc-core',
  :git => 'git@github.com:ConclusionMC/puppet-core.git',
  :ref => 'v6.6.0'
mod 'cmc-cis_linux',
  :git => 'git@github.com:ConclusionMC/puppet-cis_linux.git',
  :ref => 'v1.1.3'
mod 'puppet-fw',
  :git => 'git@github.com:ConclusionMC/puppet-fw.git',
  :ref => 'v0.1.2'
mod 'example42-network', '3.3.5'
mod 'saz-timezone', '3.3.0'
mod 'puppetlabs-ntp', '4.1.2'
mod 'cmc-postfix',
  :git => 'git@github.com:ConclusionMC/puppet-postfix.git',
  :ref => 'v1.0.0'
mod 'puppet-logrotate', '3.2.0'
mod 'cmc-facts_core',
  :git => 'git@github.com:ConclusionMC/facts_core.git',
  :ref => 'v0.1.1'
mod 'ghoneycutt-ssh', '3.49.0'
